# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [55]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [57]:
# your code here
np.__version__

'1.20.3'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [66]:
# Method 1
a = np.random.rand(2, 3, 5)
a

array([[[0.36507249, 0.46182596, 0.88585323, 0.80985877, 0.58278716],
        [0.52814845, 0.71183255, 0.36023499, 0.67367505, 0.25072014],
        [0.12377062, 0.84585166, 0.19200417, 0.52487184, 0.27265805]],

       [[0.41567369, 0.63005424, 0.83094364, 0.95700994, 0.36272421],
        [0.46873633, 0.12816508, 0.22573911, 0.773382  , 0.23061898],
        [0.4172743 , 0.4181096 , 0.8061013 , 0.99231974, 0.89321193]]])

In [144]:
# Method 2
a = np.random.randn(2, 3, 5)
a

array([[[-0.60618427, -1.5456854 , -0.55506834, -0.20713791,
          0.18408832],
        [-0.63257699,  0.64976872,  1.18544901,  0.80733394,
         -0.07894507],
        [ 0.39515567,  1.1107711 , -0.50785294, -0.298463  ,
         -1.32408696]],

       [[-0.17670972,  0.37431948,  1.51018155, -1.03585653,
         -2.15939565],
        [ 0.88211684, -1.60471274,  0.47059613, -0.21003302,
          1.09005239],
        [-0.17466841, -0.46444466,  1.71789308,  0.83897087,
         -2.25928449]]])

In [147]:
# Method 3
a = np.random.random((2,3,5))
a

array([[[0.47020874, 0.07512496, 0.54063964, 0.09357563, 0.09772088],
        [0.55885522, 0.00898846, 0.11061172, 0.55773027, 0.73685716],
        [0.18204807, 0.64355128, 0.04522586, 0.37361981, 0.88323826]],

       [[0.42388851, 0.4834682 , 0.97226976, 0.54015006, 0.43195413],
        [0.8607179 , 0.716402  , 0.8434714 , 0.41010686, 0.70901482],
        [0.14539898, 0.28560081, 0.09660968, 0.87105211, 0.01763644]]])

#### 4. Print *a*.


In [148]:
# your code here
print(a)

[[[0.47020874 0.07512496 0.54063964 0.09357563 0.09772088]
  [0.55885522 0.00898846 0.11061172 0.55773027 0.73685716]
  [0.18204807 0.64355128 0.04522586 0.37361981 0.88323826]]

 [[0.42388851 0.4834682  0.97226976 0.54015006 0.43195413]
  [0.8607179  0.716402   0.8434714  0.41010686 0.70901482]
  [0.14539898 0.28560081 0.09660968 0.87105211 0.01763644]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [159]:
# your code here
b = np.array([[[1,1], [1,1], [1,1]], [[1,1], [1,1], [1,1]], 
              [[1,1], [1,1], [1,1]], [[1,1], [1,1], [1,1]], 
              [[1,1], [1,1], [1,1]]])

#### 6. Print *b*.


In [160]:
# your code here
print(b)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [161]:
# your code here
print(a.shape)
print(b.shape)
# the shapes are not the same

(2, 3, 5)
(5, 3, 2)


#### 8. Are you able to add *a* and *b*? Why or why not?


In [162]:
# your answer here
print(a+b)
# we cannot add a and b because their shapes are different

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [163]:
# your code here
c = b.T
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [164]:
# your code/answer here
d = a + c
d

array([[[1.47020874, 1.07512496, 1.54063964, 1.09357563, 1.09772088],
        [1.55885522, 1.00898846, 1.11061172, 1.55773027, 1.73685716],
        [1.18204807, 1.64355128, 1.04522586, 1.37361981, 1.88323826]],

       [[1.42388851, 1.4834682 , 1.97226976, 1.54015006, 1.43195413],
        [1.8607179 , 1.716402  , 1.8434714 , 1.41010686, 1.70901482],
        [1.14539898, 1.28560081, 1.09660968, 1.87105211, 1.01763644]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [167]:
# your code/answer here
print(a)
print('\n')
print(d)

# the values of d is higher than the valuse in a by "1"

[[[0.47020874 0.07512496 0.54063964 0.09357563 0.09772088]
  [0.55885522 0.00898846 0.11061172 0.55773027 0.73685716]
  [0.18204807 0.64355128 0.04522586 0.37361981 0.88323826]]

 [[0.42388851 0.4834682  0.97226976 0.54015006 0.43195413]
  [0.8607179  0.716402   0.8434714  0.41010686 0.70901482]
  [0.14539898 0.28560081 0.09660968 0.87105211 0.01763644]]]


[[[1.47020874 1.07512496 1.54063964 1.09357563 1.09772088]
  [1.55885522 1.00898846 1.11061172 1.55773027 1.73685716]
  [1.18204807 1.64355128 1.04522586 1.37361981 1.88323826]]

 [[1.42388851 1.4834682  1.97226976 1.54015006 1.43195413]
  [1.8607179  1.716402   1.8434714  1.41010686 1.70901482]
  [1.14539898 1.28560081 1.09660968 1.87105211 1.01763644]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [168]:
# your code here
e = a * c
e

array([[[0.47020874, 0.07512496, 0.54063964, 0.09357563, 0.09772088],
        [0.55885522, 0.00898846, 0.11061172, 0.55773027, 0.73685716],
        [0.18204807, 0.64355128, 0.04522586, 0.37361981, 0.88323826]],

       [[0.42388851, 0.4834682 , 0.97226976, 0.54015006, 0.43195413],
        [0.8607179 , 0.716402  , 0.8434714 , 0.41010686, 0.70901482],
        [0.14539898, 0.28560081, 0.09660968, 0.87105211, 0.01763644]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [169]:
# your code/answer here
# YEs, e equals to a because here it's a multiplication by elements (not multiplication by matrix)

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [170]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

1.9722697594428036
1.008988455381938
1.4395245881825316


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [173]:
# your code here
f = np.empty([2, 3, 5])
f

array([[[0.47020874, 0.07512496, 0.54063964, 0.09357563, 0.09772088],
        [0.55885522, 0.00898846, 0.11061172, 0.55773027, 0.73685716],
        [0.18204807, 0.64355128, 0.04522586, 0.37361981, 0.88323826]],

       [[0.42388851, 0.4834682 , 0.97226976, 0.54015006, 0.43195413],
        [0.8607179 , 0.716402  , 0.8434714 , 0.41010686, 0.70901482],
        [0.14539898, 0.28560081, 0.09660968, 0.87105211, 0.01763644]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [179]:
# your code here
f = [[[25 if d_min < i < d_mean
      else 75 if d_mean < i < d_max
      else 50 if i == d_mean 
      else 0 if i == d_min
      else 100 for i in list1] for list1 in list2] for list2 in d]
print(f)

[[[75, 25, 75, 25, 25], [75, 0, 25, 75, 75], [25, 75, 25, 25, 75]], [[25, 75, 100, 75, 25], [75, 75, 75, 25, 75], [25, 25, 25, 75, 25]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [180]:
# your code here
print(d)
print(f)

[[[1.47020874 1.07512496 1.54063964 1.09357563 1.09772088]
  [1.55885522 1.00898846 1.11061172 1.55773027 1.73685716]
  [1.18204807 1.64355128 1.04522586 1.37361981 1.88323826]]

 [[1.42388851 1.4834682  1.97226976 1.54015006 1.43195413]
  [1.8607179  1.716402   1.8434714  1.41010686 1.70901482]
  [1.14539898 1.28560081 1.09660968 1.87105211 1.01763644]]]
[[[75, 25, 75, 25, 25], [75, 0, 25, 75, 75], [25, 75, 25, 25, 75]], [[25, 75, 100, 75, 25], [75, 75, 75, 25, 75], [25, 25, 25, 75, 25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [181]:
# your code here
f = [[['B' if d_min < i < d_mean
      else 'D' if d_mean < i < d_max
      else 'C' if i == d_mean 
      else 'A' if i == d_min
      else 'E' for i in list1] for list1 in list2] for list2 in d]
print(f)

[[['D', 'B', 'D', 'B', 'B'], ['D', 'A', 'B', 'D', 'D'], ['B', 'D', 'B', 'B', 'D']], [['B', 'D', 'E', 'D', 'B'], ['D', 'D', 'D', 'B', 'D'], ['B', 'B', 'B', 'D', 'B']]]
